---
# Source: hlf-couchdb/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cdb-peer1-hlf-couchdb
  labels:
    app: hlf-couchdb1
type: Opaque
data:
  COUCHDB_USERNAME:  "YWRtaW5pc3RyYXRvcg=="
  COUCHDB_PASSWORD: "UGFzc3cwcmQxIQ=="
---
# Source: hlf-couchdb/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cdb-peer1-hlf-couchdb
  labels:
    app: hlf-couchdb1
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
# Source: hlf-couchdb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cdb-peer1-hlf-couchdb
  labels:
    app: hlf-couchdb1
spec:
  type: NodePort
  ports:
    - nodePort: 30084
      targetPort: 5984
      port: 30084
      protocol: TCP
      name: couchdb
  selector:
    app: hlf-couchdb1
---
# Source: hlf-couchdb/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cdb-peer1-hlf-couchdb
  labels:
    app: hlf-couchdb1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hlf-couchdb1
  template:
    metadata:
      labels:
        app: hlf-couchdb1
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: cdb-peer1-hlf-couchdb
      containers:
        - name: hlf-couchdb1
          image: "hyperledger/fabric-couchdb:0.4.10"
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: cdb-peer1-hlf-couchdb
          volumeMounts:
          - mountPath: /opt/couchdb/data
            name: data
          ports:
            - name: couchdb
              containerPort: 5984
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 5984
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 5984
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            {}
---
apiVersion: v1
kind: Secret
metadata:
  name: cdb-peer2-hlf-couchdb
  labels:
    app: hlf-couchdb2
type: Opaque
data:
  COUCHDB_USERNAME:  "YWRtaW5pc3RyYXRvcg=="
  COUCHDB_PASSWORD: "UGFzc3cwcmQxIQ=="
---
# Source: hlf-couchdb/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cdb-peer2-hlf-couchdb
  labels:
    app: hlf-couchdb2
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
# Source: hlf-couchdb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cdb-peer2-hlf-couchdb
  labels:
    app: hlf-couchdb2
spec:
  type: NodePort
  ports:
    - nodePort: 30184
      targetPort: 5984
      port: 30184
      protocol: TCP
      name: couchdb
  selector:
    app: hlf-couchdb2
---
# Source: hlf-couchdb/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cdb-peer2-hlf-couchdb
  labels:
    app: hlf-couchdb2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hlf-couchdb2
  template:
    metadata:
      labels:
        app: hlf-couchdb2
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: cdb-peer2-hlf-couchdb
      containers:
        - name: hlf-couchdb2
          image: "hyperledger/fabric-couchdb:0.4.10"
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: cdb-peer2-hlf-couchdb
          volumeMounts:
          - mountPath: /opt/couchdb/data
            name: data
          ports:
            - name: couchdb
              containerPort: 5984
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 5984
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 5984
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            {}
---
